Vectorized populate_trans_mat
miraep8/rendseq pull request #11
Opened 2022-04-12 21:03 UTC by conniesaur

Vectorized populate_trans_mat in make_peaks.py for an 8x speed improvement. Confirmed it gives the exact same output as the original function.

2022-04-12 21:37 UTC, julianstanley requested changes
This looks great to me--an 8x speed improvement holy moly, great job! I'd recommend just making the .gitignore more general before merging.

2022-04-12 21:37 UTC, julianstanley commented on .gitignore
> +rendseq/__pycache__/zscores.cpython-310.pyc
Just adding `rendseq/__pycache__/*` and `rendseq/.ipynb_checkpoints/*` should work for these four lines, right?

2022-04-13 00:31 UTC, miraep8 commented
Hey Connie! Thanks for making this pull request :)  I agree - all looks good to me!  The .gitignore suggestion sounds reasonable to me, so once that is committed I will ahead and approve the PR!   Thanks for making the hmm peak calling better!

2022-04-13 00:35 UTC, miraep8 commented on rendseq/make_peaks.py
> +        paths += np.log(trans_m)                     # adds log(trans_m) element-wise
great improvement!  I love the use of numpy here :)

2022-04-13 00:42 UTC, miraep8 commented on .gitignore
> +rendseq/__pycache__/zscores.cpython-310.pyc
Seems like a reasonable suggestion - though alternatively I think the *.pyc line you already have is actually replaces rendseq/__pycache__/* and is more readable.  Then for the jupyter notebook stuff could do *.ipynb_checkpoints.* :)

2022-04-13 14:43 UTC, miraep8 commented
I am actually going to go ahead and approve this pull request - we can make the .gitignore a bit more general in another pull request and I want to make sure Connie's contributions get incorporated before I start doing weird things to the CI so she doesn't have to deal with that!

2022-04-13 14:43 UTC, merged

2022-04-13 15:27 UTC, conniesaur commented
Sounds good, I'll definitely take care of the .gitignore prior to my next pull request!